name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev cmake libffi-dev libssl-dev curl wget
        
    - name: Pre-setup Android SDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        # تنزيل Android SDK Command Line Tools مباشرة
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline-tools.zip
        mkdir -p ~/.buildozer/android/platform/android-sdk
        unzip -q /tmp/cmdline-tools.zip -d ~/.buildozer/android/platform/android-sdk/
        mv ~/.buildozer/android/platform/android-sdk/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools-temp
        mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        mv ~/.buildozer/android/platform/android-sdk/cmdline-tools-temp/* ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/
        
        # قبول التراخيص
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        
        # تثبيت build-tools إصدار مدعوم
        ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-34" "platform-tools"
        
    - name: Install Buildozer and dependencies
      run: pip install buildozer cython
        
    - name: Build APK with Buildozer
      run: |
        buildozer android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: packet-sender-apk
        path: bin/*.apk
        retention-days: 30
